name: Updater
on:
  workflow_dispatch:
    inputs:
      ip:
        description: The IP Address of a Proxy server
        required: true
jobs:
  proxy:
    runs-on: ubuntu-latest
    env:
      PROXY_ADDR: ${{ github.event.inputs.ip }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      # Run the update
      - name: Serve
        run: go run client/client.go
